const GLOBAL_SANITY_CLIENT_API_VERSION: string = '2024-06-01'
const GLOIBAL_SANITY_CMS_PAGE_REVIEW_TITLE_SIZE_LIMIT: number = 20

export const globalVariables = {
  SANITY_API_VERSION: GLOBAL_SANITY_CLIENT_API_VERSION,
  CMS_PAGE_REVIEW_TITLE_SIZE_LIMIT: GLOIBAL_SANITY_CMS_PAGE_REVIEW_TITLE_SIZE_LIMIT,
}