const GLOBAL_SANITY_CLIENT_API_VERSION: string = '2024-06-01'
const GLOIBAL_SANITY_CMS_PAGE_REVIEW_TITLE_SIZE_LIMIT: number = 20
const GLOBAL_SANITY_PORTFOLIO_ITEM_MAX_WEIGHT: number = 300
const GLOBAL_SANITY_PORTFOLIO_ITEM_DEFAULT_WEIGHT: number = 300

export const globalVariables = {
  SANITY_API_VERSION: GLOBAL_SANITY_CLIENT_API_VERSION,
  CMS_PAGE_REVIEW_TITLE_SIZE_LIMIT: GLOIBAL_SANITY_CMS_PAGE_REVIEW_TITLE_SIZE_LIMIT,
  PORTFOLIO_ITEM_MAX_WEIGHT: GLOBAL_SANITY_PORTFOLIO_ITEM_MAX_WEIGHT,
  PORTFOLIO_ITEM_DEFAULT_WEIGHT: GLOBAL_SANITY_PORTFOLIO_ITEM_DEFAULT_WEIGHT,
}